export const optionIntensityRates = [
  { option: 'zeh', defaultValue: 1, range: [0, 1] },
  { option: 'self-re', defaultValue: 1, range: [0, 1] },
  { option: 'grid-re', defaultValue: 1, range: [] },
  { option: 'com-house', defaultValue: 1, range: [0, 1] },
  { option: 'insrenov', defaultValue: 1, range: [0, 1] },
  { option: 'clothes-home', defaultValue: 0.5, range: [] },
  { option: 'ec', defaultValue: 1, range: [0, 1] },
  { option: 'ac', defaultValue: 0.5, range: [] },
  { option: 'led', defaultValue: 0.5, range: [] },
  { option: 'enenudge', defaultValue: 0.5, range: [] },
  { option: 'telework', defaultValue: 0.5, range: [] },
  { option: 'closework', defaultValue: 0.5, range: [] },
  { option: 'mictourism', defaultValue: 0.25, range: [] },
  { option: 'closeservice', defaultValue: 0.5, range: [] },
  { option: 'dailyshift', defaultValue: 0.25, range: [] },
  { option: 'longshift', defaultValue: 0.25, range: [] },
  { option: 'rideshare', defaultValue: 0.25, range: [] },
  { option: 'carshare', defaultValue: 0.25, range: [] },
  { option: 'car-ev-phv', defaultValue: 1, range: [0, 1] },
  { option: 'car-ev-phv-re', defaultValue: 1, range: [0, 1] },
  { option: 'vegan', defaultValue: 0.25, range: [] },
  { option: 'vegetarian', defaultValue: 0.25, range: [] },
  { option: 'white-meat-fish', defaultValue: 0.25, range: [] },
  { option: 'guide-meal', defaultValue: 0.5, range: [] },
  { option: 'guide-snack-drink', defaultValue: 0.25, range: [] },
  { option: 'loss', defaultValue: 0.25, range: [] },
  { option: 'seasonal', defaultValue: 0.25, range: [] },
  { option: 'local', defaultValue: 0.25, range: [] },
  { option: 'clothes-accessory', defaultValue: 0.25, range: [] },
  { option: 'electronics-furniture', defaultValue: 0.25, range: [] },
  { option: 'hobby', defaultValue: 0.25, range: [] },
  { option: 'consumables', defaultValue: 0.25, range: [] },
  { option: 'books', defaultValue: 0.25, range: [] },
  { option: 'eco-tourism', defaultValue: 0.25, range: [] }
]
